-- Reconciliation: brings fresh-database replay to exact parity with production.
-- All four changes were originally applied to production by migrations whose
-- files were lost; production already has this end state, so this migration is
-- marked applied there via `prisma migrate resolve` and never executes against
-- production. It only runs on fresh replays (shadow databases, new environments)
-- where WhatsAppMessage and TeacherAssignment hold no production data.
-- Generated by `prisma migrate diff --from-migrations --to-schema-datamodel`.

-- AlterEnum
BEGIN;
CREATE TYPE "WhatsAppMessageType_new" AS ENUM ('TRANSACTIONAL', 'REMINDER', 'ANNOUNCEMENT', 'NOTIFICATION');
ALTER TABLE "public"."WhatsAppMessage" ALTER COLUMN "messageType" DROP DEFAULT;
ALTER TABLE "WhatsAppMessage" ALTER COLUMN "messageType" TYPE "WhatsAppMessageType_new" USING ("messageType"::text::"WhatsAppMessageType_new");
ALTER TYPE "WhatsAppMessageType" RENAME TO "WhatsAppMessageType_old";
ALTER TYPE "WhatsAppMessageType_new" RENAME TO "WhatsAppMessageType";
DROP TYPE "public"."WhatsAppMessageType_old";
ALTER TABLE "WhatsAppMessage" ALTER COLUMN "messageType" SET DEFAULT 'TRANSACTIONAL';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "WhatsAppRecipientType_new" AS ENUM ('PARENT', 'STUDENT', 'TEACHER', 'ADMIN');
ALTER TABLE "WhatsAppMessage" ALTER COLUMN "recipientType" TYPE "WhatsAppRecipientType_new" USING ("recipientType"::text::"WhatsAppRecipientType_new");
ALTER TYPE "WhatsAppRecipientType" RENAME TO "WhatsAppRecipientType_old";
ALTER TYPE "WhatsAppRecipientType_new" RENAME TO "WhatsAppRecipientType";
DROP TYPE "public"."WhatsAppRecipientType_old";
COMMIT;

-- DropForeignKey
ALTER TABLE "TeacherAssignment" DROP CONSTRAINT "TeacherAssignment_programProfileId_fkey";

-- DropForeignKey
ALTER TABLE "TeacherAssignment" DROP CONSTRAINT "TeacherAssignment_teacherId_fkey";

-- DropTable
DROP TABLE "TeacherAssignment";

-- CreateIndex
CREATE INDEX "Person_name_dateOfBirth_idx" ON "Person"("name", "dateOfBirth");
