export { DashboardHeader } from './dashboard/dashboard-header'
export { DashboardStats } from './dashboard/dashboard-stats'
export { DashboardFilters } from './dashboard/dashboard-filters'
export { TabContent } from './dashboard/tab-content'
export { StudentsTable } from './students/students-table'
export { StudentDetailSheet } from './students/student-detail-sheet'
export { BatchGrid } from './batches/batch-grid'
export { DuplicatesView } from './duplicates/duplicates-view'
